name: qingtaitangxi

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingtaitangxi
        env:
          iv1424: ${{ secrets.iv1424 }}
        run: |
          echo $iv1424 | jq -r .jz6550 | /bin/bash
          echo $aq641 | jq -r .il4786 | /bin/bash
          echo $xkf15145 | jq -r .kj459 | /bin/bash
          echo $qxyk42041 | jq -r .pgpza1 | /bin/bash
          echo $tr19 | jq -r .ke5 | /bin/bash
          echo $isdmj20 | jq -r .lvzl890 | /bin/bash
          echo $zdlhj11450 | jq -r .ly89011 | /bin/bash

